global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: tasksystem
    static_configs: #Se o endpoint for fixo. Por exemplo, sem usar kubernets, sem escalar ou otras coisas.
      - targets: ['localhost:3000']
        